language: node_js
node_js:
- '0.12'
before_install:
- npm install npm -g
before_script:
- npm install
script: npm run ci
addons:
  sauce_connect: true
env:
  global:
    - secure: LNkgyXNMcreOpKRfnIc22NvSZn7ME2LolQPTZK2Y18NXDb4LaShH0i4pTtTbQXqLHA2a9JVYK4poJyAqPB7GD2E3DNEeivA6xmiA0TrgSVA0smd6cMxJIouSSHs4EUuI1rN8sp7goPD6LZBZcrTBe4rLjB+rqJPIM8XgoDVxKGImTXp10EytHR6aVX5w52Ibn7viPg7KWPp9W+e+PUkaKoBhgVnRi/kXAIDzykP6SyhnI5gqPgghsvINotl3vqWgJXesT158P0Cer6eiLCpFhZtsMDlYJS78qHno8YrJYkXieyfmY4UIG2UrSvlLAPT8/YuVFxIjlpoeofWsCUdmD45DNlRQKoFr/VkrXgAxtKupZ4y7k/DsZ460IP+Hytz+RHhODwkpo6C/PbCrp3pNiZ9AdGz/nYm7XixwlEIc1J3lnD9KUx9xewGX9EGZt0Pm6uOTpVQUF2E5nWL4oMI+LK3VYOl4Jl9fuHTgYkooW3CdxeTR6tOJ8P93On13yaYkTRTkHq/AgTsk5DCEl9kL8+r4xuzMcPvT+u4oMhf3KQO56CI3+KtxsWxE3ZbKlc1Zu16Zaa2KNsif8EkPXo35+N4p4mo7+hpXiOEwO3yGirev5tn4CuTknldlUbi+C716UsKv/uFdyaoAjGygRvyIhdZ3I3jN+u4safBKP8zsqGI=
    - secure: W3SOapGStzBd721iFmcA8qGV9SrunfWkWt2sZgpy85j5f1ex3q5/IYRlVaP4mNkxNCQ6jhLKhVitwAJHB9zlvgVrY2RJySyX25lOYIogNANsAIjEUuyJtRhEwbnhRdQwb4P5kTvwl7HdUMHFpHVNBh/EqW/Ei5OE4LCWvsZmEYhLKant/XLAfu9V+QVgRamm+ofrBVlfxRu6DpVir9/q+1sph6Ip7iPVTDQyUqBsL+Aee8C4GnXIUJQ88IrLIo7f4skXocQdAPp2ovDWynYKmnxdBNP8Ql/Yxa91hPiW8x9BXYdFf/sKhYiOyGjuB6NCsOIHSx/FG3JxM9KcaPH0lhjcRb8O9hLehlmS2tmzRh/u72Geo+CsDi+p4adsnswtGWp/Sea105e9yCOSSEzQ8NyFOAuN+yPwOBX75Lo6RvA8AY30Z+lkPzuDYtMBwVlHoVmJAgyoMQByGPZdn2WP8fQfFhr55mCrOLG2Oi/AgSGClBWL2Ok9lmSZE77hFSm8Nf/lbZpELAQA4yOtepe6K3sw1+fprSbXzgxTmaEBh8eiUsuke7i8ASTKyAErXqKBsCgQ6InUXdHNrGQB3F606au+OG84ynqTn7W3YiR2R3+ARczTVdBgx3JGpPj+8gW0IC7tfdohYZdn6R//aE5uPIClf/wpehC7F02Kii06z7k=
